language: java
#jdk: oraclejdk7
before_install:
#  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -xzf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=~/build/capedev/sf_nomnom/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter platform-tools,android-15 --no-ui --force
  - echo $ANDROID_HOME
  - ls $ANDROID_HOME
  - ls $ANDROID_HOME/platform-tools
  - android update project -p .